const UnitStates = {
  IDLE: "IDLE",
  SPAWN: "SPAWN",
  ATTACK: "ATTACK",
  ATTACK_COOLDOWN: "ATTACK_COOLDOWN",
  MOVING_TO_ATTACK: "MOVING_TO_ATTACK",
  MOVING: "MOVING",
  DEFEND: "DEFEND",
};

const UnitClasses = {
  LIGHT: "LIGHT",
  MEDIUM: "MEDIUM",
  HEAVY: "HEAVY",
  BUILDING: "BUILDING",
};
